### ISSUE TITLE
minor draft change

### ISSUE THREAD

**Issue by gregbo** [paulehoffman/draft-hoffman-random-candidate-selection#1]
In the Selecting _D_ section:

On the day that the CA announced for the selection of D, the CA goes the the source they announced and gets D. After the CA retrieves D from the announced source, they encode D as a UTF-8 string. In the example of the FTSE 100 Index, a closing value for the day announced at the beginning of the ceremony might be "7623.10". This would be encoded in UTF-8 as the string of characters whose hex value is 0x373632372e3130.

s/0x373632372e3130/0x373632332e3130/

I assume you want the resulting changes of section 3.4 of this draft to be "This would be encoded in UTF-8 as the string of
   characters whose value is U+373632332e3130."

**Comment by paulehoffman** [comment]
Yipes! Very good catch, thank you. Fixed in 0651fba..65f9ab7
