### ISSUE TITLE
another minor draft change

### ISSUE THREAD

**Issue by gregbo** [paulehoffman/draft-hoffman-random-candidate-selection#2]
In the Use of the FTSE 100 Index section:

Note that the location for sources of daily closing values can change over time. The CA must check that the source they intende to use is still active, and still available when the ceremony starts.

s/intende/intend/

or to make the second sentence less grammatically (in English) awkward:

The CA must check that the intended source is still active, and still available when the ceremony starts.

**Comment by paulehoffman** [comment]
Excellent, thanks! Fixed in the source.
