### ISSUE TITLE
another source of randomness

### ISSUE THREAD

**Issue by gregbo** [paulehoffman/draft-hoffman-random-candidate-selection#3]
Would you consider average (mean) world temperature as a source of randomness?  For example, [Climate Reanalyzer](https://climatereanalyzer.org/clim/t2_daily/) provides such data.  A bonus feature is [daily data is provided from 1979 to the present in JSON format](https://climatereanalyzer.org/clim/t2_daily/json/cfsr_world_t2_day.json), so selecting _D_ can be automated and tested for randomness.  (Arguably, the WSJ site provides FTSE 100 closing values in CSV format, but only about three months of data is available.)

**Comment by paulehoffman** [comment]
A big part of choosing a source of randomness is how assured will all the candidates be that the source cannot be manipulated by any candidate or the CA. The prices of an index of stocks, reported in a recognized place, is pretty unimpeachable. A collection of temperatures from a not-well-known organization is trustworthy to as wide of an audience.

**Comment by gregbo** [comment]
For what it's worth, I'd consider other (non-financial) sources of randomness.  The Climate Reanalyzer site was just an example that had what IMO are redeeming qualities, such as a straightforward, automatable means of querying the data.  As it turns out, it is possible to obtain historical FTSE 100 data over the same timespan as that of Climate Reanalyzer, but it's less straightforward, as it requires filling in a form with the timespan, and extracting the data from a CSV file, which doesn't have dates in Y2K format.  The FTSE 100 (and other financial indexes) are also subject to data gaps, because the markets aren't open every day, and trading could be halted, not to mention the WSJ site could be hacked.  On the other hand, Climate Reanalyzer data (if collected reliably) would be available every day.

There are other sources of scientific data such as the NOAA and USGS that I would find acceptable (provided that the information is collected reliably) that have arguably better reputations than Climate Reanalyzer.

I would not have brought up this issue if it had not been for some of the discussions on the IETF discussion list during 2020-2022 concerning randomness with regards to Nomcom selection.  Perhaps you consider your proposal to be a "lite" version of the current RFC 3797 method, but others might have concerns, based upon those discussions.
